[general]

#### Address & Root dir
# host = "::"
port = 8090
root = "./"

#### Health-check endpoint (GET or HEAD `/health`)
health = true

#### Logging
log-level = "info"

#### CORS & Security headers
# security-headers = true
cors-allow-origins = "*"

#### Directory listing
directory-listing = false

#### Directory listing sorting code
directory-listing-order = 1

#### Directory listing content format
directory-listing-format = "html"

#### Directory listing download format
directory-listing-download = []
        
[advanced]

[[advanced.headers]]
source = "**/*.{html,js,css}"
[advanced.headers.headers]
Access-Control-Allow-Origin = "*"
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"
